### ISSUE TITLE
Add tutorial for external volumes to Docker deployment

### ISSUE THREAD

**Issue by luk27official** [cusbg/p2rank-framework#5]
Consulted in [this pull request](https://github.com/cusbg/prankweb/pull/100).
As long as the docker-compose volumes are kept external, a tutorial on how to create those volumes with a specific mapping should be added to the Wiki.

**Comment by skodapetr** [comment]
They are now part of the [Deploy with Docker](https://github.com/cusbg/p2rank-framework/wiki/PrankWeb-deploy-with-Docker) wiki page.
