### ISSUE TITLE
wiki dockerfile path

### ISSUE THREAD

**Issue by ojcharles** [cusbg/p2rank-framework#6]
Hi small issue but it's bugging me, thanks for making great tools!

page: https://github.com/cusbg/p2rank-framework/wiki/P2Rank-Deploy-Docker

text with error: Build docker image docker build --build-arg UID=$(id -u ${USER}) --build-arg GID=$(id -g ${USER}) -t p2rank -f runtime/Dockerfile .

text should be: Build docker image docker build --build-arg UID=$(id -u ${USER}) --build-arg GID=$(id -g ${USER}) -t p2rank -f administration/Dockerfile .

**Comment by skodapetr** [comment]
Thank you for the report. Should be fixed by now.
